### ISSUE TITLE
Segfault in x86, using clang

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/desmume2015#21]
The core run some time with the content, but it gets a segfault. If you build with debug=1, core works! Then I builded with debug=1 and OPTIMIZE = -O3, to get the segfault (are there any better way to do this?):

```
Starting program: /usr/bin/retroarch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[New Thread 0xb0560b40 (LWP 20972)]
[Thread 0xb0560b40 (LWP 20972) exited]
Microphone successfully inited.
DeSmuME 0.9.11 svn0 x86-JIT
Attempting change to 3d core to: SoftRasterizer
SoftRast Initialized with cores=1
read_7zip_file: Openend archive /home/xubuntu/Downloads/0434 - New Super Mario Bros. (U)(Psyfer).7z. Now trying to extract 0434 - New Super Mario Bros. (U)(Psyfer).nds
RetroArch [WARN] :: rarch_log_libretro :: [libretro WARN] :: Save directory is not defined. Fallback on using SYSTEM directory ...

ROM game code: A2DE
ROM serial: NTR-A2DE-USA
ROM chipID: 00001FC2
ROM internal name: NEW MARIO
ROM developer: Nintendo

Slot1 auto-selected device type: Retail MC+ROM
Slot2 auto-selected device type: None (0xFF)
Backup size: 64 Kbit
CPU mode: JIT
JIT: max block size 100 instruction(s)
Already decrypted.
[New Thread 0xb0560b40 (LWP 21006)]

Program received signal SIGSEGV, Segmentation fault.
0x9ae548ef in ?? () from /usr/lib/libretro/desmume_libretro.so

(gdb) bt full
#0  0x9ae548ef in ?? () from /usr/lib/libretro/desmume_libretro.so
No symbol table info available.
#1  0x9ae541cb in ?? () from /usr/lib/libretro/desmume_libretro.so
No symbol table info available.
#2  0x9ae53a9d in ?? () from /usr/lib/libretro/desmume_libretro.so
No symbol table info available.
#3  0x9ae5335b in ?? () from /usr/lib/libretro/desmume_libretro.so
No symbol table info available.
#4  0x9ae521a9 in ?? () from /usr/lib/libretro/desmume_libretro.so
No symbol table info available.
#5  0x9ae93dcd in ?? () from /usr/lib/libretro/desmume_libretro.so
No symbol table info available.
#6  0x9ae94a32 in ?? () from /usr/lib/libretro/desmume_libretro.so
No symbol table info available.
#7  0x9ae3724a in ?? () from /usr/lib/libretro/desmume_libretro.so
No symbol table info available.
#8  0x9ae3bf57 in ?? () from /usr/lib/libretro/desmume_libretro.so
No symbol table info available.
#9  0x9aea7dd0 in retro_run () from /usr/lib/libretro/desmume_libretro.so
No symbol table info available.
#10 0x0805e3b1 in ?? ()
No symbol table info available.
#11 0x0805286d in ?? ()
No symbol table info available.
#12 0xb6828a83 in __libc_start_main (main=0x80527d0, argc=1, argv=0xbffff244, init=0x80f3bd0, fini=0x80f3c40, rtld_fini=0xb7fed180 <_dl_fini>, stack_end=0xbffff23c) at libc-start.c:287
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {-1231314944, 0, 0, 0, -1815781075, 1764918591}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x8052920}, data = {prev = 0x0, 
              cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#13 0x08052941 in ?? ()
No symbol table info available.
```

**Comment by sergiobenrocha2** [comment]
I forgot to say, trying in Ubuntu 14.04.
